version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: selling_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    ports:
      - '3307:3306'
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: selling_app
    ports:
      - '8080:8080'
    environment:
      DECODING_KEY: ${DECODING_KEY_CURRENT}
      END_POINT_CURRENT: ${END_POINT_CURRENT}