version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: selling_db
    environment:
      - MYSQL_DB = ${DB_NAME}
      - MYSQL_USER = ${DB_USER}
      - MYSQL_PASS = ${DB_PASS}
    ports:
      - '3306'

  app:
    image: 'amazoncorretto:21'
    environment:
      - DECODING_KEY = ${DECODING_KEY_CURRENT}
      - END_POINT_CURRENT = ${END_POINT_CURRENT}
    ports:
      - '8080'