spring:
  application:
    name: sellingService
  profiles:
    active: "prod"

  #  docker:
#    compose:
#      enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/selling_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: selling_user
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver


end_point_current: ${END_POINT_CURRENT}
curr_key: ${ENCODING_KEY_CURRENT}

server:
  port: 8080

client_id: ${CLIENT_ID}
client_secret: ${CLIENT_SECRET}

naver_request_url: ${NAVER_REQUEST_URL}
naver_request_info_url: ${NAVER_REQUEST_INFO_URL}
naver_request_token_url: ${NAVER_TOKEN_REQUEST_URL}

naver_redirect: ${NAVER_CALL_BACK_URL}