spring:
  application:
    name: sellingService

  docker:
    compose:
      enabled: false


end_point_current: ${END_POINT_CURRENT}
curr_key: ${ENCODING_KEY_CURRENT}

server:
  port: 8080

client_id: ${CLIENT_ID}
client_secret: ${CLIENT_SECRET}

naver_request_url: ${NAVER_REQUEST_URL}
naver_request_info_url: ${NAVER_REQUEST_INFO_URL}
naver_request_token_url: ${NAVER_TOKEN_REQUEST_URL}

naver_redirect: ${NAVER_CALL_BACK_URL}