ENCODING_KEY_CURRENT = eHo%2B7KF2EwEZsGk0Ci9DrNxly8UUE1XRYUW0BRMF3%2F7wvyTib6bRUdVbI8JzoWm6sEFBmuhRx6e9xs2oSMaZyA%3D%3D
DECODING_KEY_CURRENT = eHo+7KF2EwEZsGk0Ci9DrNxly8UUE1XRYUW0BRMF3/7wvyTib6bRUdVbI8JzoWm6sEFBmuhRx6e9xs2oSMaZyA==
ENCODING_KEY_INFO = eHo%2B7KF2EwEZsGk0Ci9DrNxly8UUE1XRYUW0BRMF3%2F7wvyTib6bRUdVbI8JzoWm6sEFBmuhRx6e9xs2oSMaZyA%3D%3D
DECODING_KEY_INFO = eHo+7KF2EwEZsGk0Ci9DrNxly8UUE1XRYUW0BRMF3/7wvyTib6bRUdVbI8JzoWm6sEFBmuhRx6e9xs2oSMaZyA==

END_POINT_CURRENT = http://apis.data.go.kr/B552845/katRealTime
END_POINT_INFO = http://apis.data.go.kr/B552845/katCode

DB_NAME  = selling_db
DB_USER = selling_user
DB_PASS = 12341234